### ISSUE TITLE
Separate calibration from calculation of indices

### ISSUE THREAD

**Issue by jamaa** [monocongo/climate_indices#109]
In some use cases, it would be beneficial to perform the calibration separately from the calculation of an index. E.g. say you want to calculate indices for multiple different forecasts, all of them based on a single calibration performed on one time series of observed values. 
Perhaps you could have a separate method for calibration which returns the calibration result, which in turn can then be passed to an index calculation method together with the time series for which the index should be computed.

**Comment by monocongo** [comment]
This can be done without too much effort, I think. If I understand correctly what you're proposing is to compute the distribution fitting parameters based on the calibration period for use with subsequent runs. I have done this before in a previous version of this code that was written in Java. It worked out to add a considerable amount of complexity to the codebase as far as data wrangling etc. (the Java NetCDF API is cumbersome) but resulted in a significant performance improvement in terms of the reduced amount of computation required, since the bulk of the computation for these indices (SPI and SPEI) is around determining the distribution fitting parameters based on the calibration period.

I may first resolve issue #108 to allow you guys to see if that's sufficient for your immediate needs, especially if you're OK with using the gamma distribution fitting since that code currently runs so much faster than does the Pearson III fitting code (see issue #100). However, if you're needing Pearson III as well then this approach is more interesting since it will feasibly save a considerable amount of processing, especially if your input datasets are large or if your computing resources are limited/costly.

**Comment by jamaa** [comment]
yes, resolving #108 first is a good idea. We will probably be sticking to the gamma distribution fitting because we have to compare with other SPI computations also done with gamma.
