### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by ghost** [monocongo/climate_indices#181]
Dear Friends, 
After configuring the environment and installing the module, I run into an issue while trying to validate the tests. I have attached a screenshot of the error. Thank you in advance for any assistance you could provide me in this regard.
Regards,
Reza

https://www.dropbox.com/s/nzuzef9xndg81io/Untitled.png?dl=0

**Comment by monocongo** [comment]
Thanks, Reza. Can you please list the steps you took before getting to this error? At first glance it appears to be some sort of `PYTHONPATH` issue since it can't find the netcdf_utils.py module, so the module may not be in the PYTHONPATH and/or the other locations where unittests.loader is searching for modules to import.

Maybe post some information about the Python and shell environments such as PYTHONPATH, etc., this may be useful to help isolate the error.

BTW I'm not very expert with this sort of thing, but this is a good way to learn...

**Comment by ghost** [comment]
Dear James,
First I created a Python environment via conda, then, I activated the environment and installed the module. When I started testing for validation according to the steps stated in https://www.drought.gov/drought/python-climate-indices I faced the aforementioned error. Anyway, I continued and I could calculate the indices for the examples provided within the directory. I don't know whether the error affects the results or not! 
However, thank you very much indeed for your kind response.
Best,

**Comment by monocongo** [comment]
Feel free to contact us again if you need any further assistance. Thanks!
