### ISSUE TITLE
Bugs in the process_grid.py

### ISSUE THREAD

**Issue by minxu74** [monocongo/climate_indices#197]
- In line 535 of [process_grid.py](https://github.com/monocongo/climate_indices/blob/32c3022d8920f2718ccb57d10f7d772a74142154/scripts/process_grid.py#L535),  the "'pet'" should be changed to "self.var_name_pet".

- The self.periodicity in process_grid.py is a string variable, but in the [compute.py](https://github.com/monocongo/climate_indices/blob/32c3022d8920f2718ccb57d10f7d772a74142154/climate_indices/compute.py#L508), it is used as Periodicity object and leads to run-timing failure.

**Comment by minxu74** [comment]
I am trying to fix them and submit a PR in days.

**Comment by monocongo** [comment]
Thank you, Min.

BTW in the develop branch, there is a new version of `process_grid.py` as well as another script which I assume will eventually replace that script, [process_grid_ucache.py](https://github.com/monocongo/climate_indices/blob/develop/scripts/process_grid_ufunc.py), in case you'd prefer to work against that rather than the code that's currently in the master branch. The issues you mention above I think have already been addressed in the develop branch, but I'm not certain. If you can give the new script a whirl on your data pleae let me know how it performs. It works well with the example datasets (nclimgrid_*lowres*.nc) but with other NetCDFs I've used as input it still has issues to be ironed out, which is why that code's not been merged into the master branch yet.

If there's anything I can do to help then just let me know.

**Comment by minxu74** [comment]
Thanks, @monocongo . Great to know that the bugs have been fixed in the develop branch. I am going to try your new code with my datasets.

**Comment by minxu74** [comment]
@monocongo I tested the process_grid_ufunc.py in the develop branch. I got results successfully for SPI, SPEI and Palmer indices using my netcdf files. Hope that the develop branch can be merged into master soon. Thanks!

**Comment by monocongo** [comment]
Thanks for the update @minxu74 ! Would it be possible for you to make available any of your input NetCDF files? That may be helpful for testing the code. My current issue with the `process_grid_ufunc.py` script is described [here](https://stackoverflow.com/questions/53108606/xarray-apply-ufunc-with-groupby-unexpected-number-of-dimensions?noredirect=1#comment93114103_53108606) -- it may help to compare your files which are working well as inputs against the files I am using which are causing errors from xarray.

**Comment by minxu74** [comment]
@monocongo  Sure. Please check my nc files in [the link](http://portal.nersc.gov/project/m1006/forclimateindices/myncfiles.tar.gz)
Please let me know anything I can help with it. Thanks a lot for sharing the software.

**Comment by monocongo** [comment]
@minxu74 Your files work fine for me as well, thanks for your help. I have tested the code with [another precipitation dataset](https://www.esrl.noaa.gov/psd/thredds/catalog/Datasets/gpcp/catalog.html?dataset=Datasets/gpcp/precip.mon.mean.nc) that works well for SPI, and with [another](https://www.esrl.noaa.gov/psd/thredds/catalog/Datasets/precl/0.5deg/catalog.html?dataset=Datasets/precl/0.5deg/precip.mon.mean.0.5x0.5.nc) that also gives the above-mentioned error from xarray. So the issue at this point is to resolve what is different about some NetCDFs that work fine with this code and the others that do not (my assumption is that `xarray.apply_ufunc()`, `xarray.open_dataset()`, and/or `xarray.DataArray.groupby()` are somehow handling the datsets in a way that I'm not correctly accounting for within the code (@shoyer et al. my have some insight here). I am actively looking into this, and of course, there may be other factors at play not yet under consideration. Most concerning to me is the fact that the latest [nClimGrid dataset files](https://www.ncei.noaa.gov/thredds/catalog/data-in-development/nclimgrid/catalog.html) when used as input also cause this error, and this is the dataset that this code was developed against and for which the code is used to produce climate indices for NCEI ([drought.gov](https://www.drought.gov/drought/data-gallery/nidis-us-map-and-data-viewer)). The nClimGrid files from earlier this year do not cause this error, and I have my suspicions as to why this is now an issue, but I am still waiting to get copies of previous NetCDF files (from archive) to confirm what's up with that particular dataset. In the meantime I may go ahead and merge the new code containing the script that utilizes `xarray.apply_ufunc()` since the errors mentioned in the original description of this issue have been fixed there, and the script leveraging `xarray.apply_ufunc()` appears to provide a significant performance gain.

**Comment by shoyer** [comment]
It might be related to the related to the order of the coordinate labels and/or the presence of duplicate coordinate values -- does the problem go away if you sort by latitude and longitude before stacking?

**Comment by monocongo** [comment]
Thanks for the suggestion, @shoyer . It appears that in fact the order of the lat/lon coordinates was the issue here. Apparently having things in ascending order is crucial to xarray for whatever reason. However, sorting of these coordinate variables before stacking seems to introduce a significant overhead on xarray which cancels out the performance improvements from `apply_ufunc()` seen with processing files that don't require sorting of the lat/lon coordinates into ascending order.

**Comment by monocongo** [comment]
I will add code into the processing script that checks for the order of lat/lon and if either of these is descending rather than ascending then it will use NCO to reverse the dimension order and return a temporary file for use in the remainder of the code. This has been the best solution so far, i.e. before running the script I will reverse the offending dimension with [NCO's ncpdq](https://linux.die.net/man/1/ncpdq), eg `ncpdq -a '-lat'` to reverse the latitude dimension, etc. There appears to be [an issue](https://github.com/nco/pynco/issues/37) with the NCO Python bindings package that is preventing this, but once that's resolved this looks to be an easy addition. In the meantime, we can just do a check on the order of the lat and lon coordinate values and if these are not ascending raise an error with a message to the user that they need to reverse the incompatible dimension(s), suggesting the NCO usage described above.

**Comment by monocongo** [comment]
Resolved by #231. Note we're no longer using `xarray.groupby` or `xarray.apply_ufunc` as those seemed to provide less performance than the use of shared memory arrays in conjunction with `numpy.apply_along_axis`
