### ISSUE TITLE
eror with multiprocessing.pool

### ISSUE THREAD

**Issue by Lixia0911** [monocongo/climate_indices#251]
Hi James, I was running the latest version on my PC in a linux environment.
1. I have already successfully got through calculating all indices with the test data. 
2. I calculated SPEI and SPI using pr and pet at the resolution (lat=180,lon=520,time=1800). It went good with SPI calculation, however, I got errors with SPEI calculation.

 **See error**

2019-01-03  17:22:47 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "process_grid.py", line 1130, in _apply_along_axis_double
    computed_array[i, j] = func1d(x[j], y[j], parameters=params["args"])
  File "process_grid.py", line 879, in _spei
    periodicity=parameters["periodicity"],
  File "/home/zhang/miniconda3/lib/python3.6/site-packages/lmoments3/distr.py", line 65, in lmom_fit
    return self._lmom_fit(lmom_ratios)
  File "/home/zhang/miniconda3/lib/python3.6/site-packages/lmoments3/distr.py", line 1277, in _lmom_fit
    raise ValueError("L-Moments invalid")
ValueError: L-Moments invalid
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_grid.py", line 1445, in <module>
    _compute_write_index(kwrgs)
  File "process_grid.py", line 775, in _compute_write_index
    args,
  File "process_grid.py", line 1039, in _parallel_process
    pool.map(_apply_along_axis_double, chunk_params)
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: L-Moments invalid
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zhang/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "process_grid.py", line 1130, in _apply_along_axis_double
    computed_array[i, j] = func1d(x[j], y[j], parameters=params["args"])
  File "process_grid.py", line 879, in _spei
    periodicity=parameters["periodicity"],
  File "/home/zhang/miniconda3/lib/python3.6/site-packages/lmoments3/distr.py", line 65, in lmom_fit
    return self._lmom_fit(lmom_ratios)
  File "/home/zhang/miniconda3/lib/python3.6/site-packages/lmoments3/distr.py", line 1277, in _lmom_fit
    raise ValueError("L-Moments invalid")
ValueError: L-Moments invalid

**Desktop (please complete the following information):**
Linux version 3.10.0-514.6.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )

**Comment by monocongo** [comment]
Thanks, @Lixia0911. If you can provide your input data I will try to reproduce on my end to see if there's anything to be done. The issue here appears to be happening within the library used for L-Moments, [lmoments3](https://pypi.org/project/lmoments3/), which is used within the Pearson fitting parts of our code. This may be remedied for now by just catching this error and setting the corresponding values to NaN, that's my first idea anyway although there may be a better way to handle this. In any event, it'll be interesting to see the data that causes this type of error so we can handle it more gracefully.

**Comment by monocongo** [comment]
Another idea is that this may be related to missing and/or mostly zero values. For example, if doing SPEI you end up with a lot of zeros after the (P - PE) step then maybe the lmoments3 code isn't clever enough to deal with that, in that it might expect/assume three or more non-zero values, etc. in order to do its work. Again this will be more evident if I can see the input data used to produce this error.

**Comment by Lixia0911** [comment]
Hi James, I'm happy to provide the input data. But I don't know how to because the datasets are about 4G. In the mean time, I'm checking the number of zero values of Pr-PET. If I can figure out the problem within the input data, I will let you know.

**Comment by monocongo** [comment]
@Lixia0911 if you want to put the data into a Google Drive or dropbox that should work, or if you can isolate the areas of your grid where the issue is happening then trim out that portion using NCO. Or use NCO to reduce the resolution of the dataset, for example something like `ncks --dmn lon,0,,4 --dmn lat,0,,4 in.nc out.nc` should do the trick (that will take every fourth point in the lat and lon dimensions, drastically reducing the size giving a lower resolution dataset).

**Comment by Lixia0911** [comment]
Thanks James. I extracted the datasets what caused the errors. Please try to download from the google drive. https://drive.google.com/drive/folders/1f37u9HOdjcFSBQglKY1x8YhonHNwdroc?usp=sharing. If this web site is not avaible, please let me know.  Thanks.

**Comment by monocongo** [comment]
Hi @Lixia0911, looking at the files the first thing I notice is that the temperature values are in degrees Kelvin, and the values are all negative. Perhaps this is causing issues with the PET computation which then percolates into the SPEI? We're getting more or less expected PET values so my assumption is that these values are actually degrees Celsius as expected, but neverthelesss it points out that we don't have sufficient units checking and this is something that can be added to further harden the code.

After doing some debugging I have found that the PET is calculated as expected except in a few places where the values are extreme, leading me to think that this is an issue with dirty data, i.e. in some places we have temperature values that go outside of the expected range and as a result we end up with wonky PET values that hose the calculation in later stages. Perhaps this has to do with the fill value being 1.0E20f rather than NaNf which is what was used in the data files used for development of this code. I don't think that this should be an issue but it's something to look into, maybe we can convert the temperature NetCDF to use NaN for fill values and see if this makes a difference.

Also, in this case, we're dealing with latitude values above where Thornthwaite is applicable. My understanding is that the Thornthwaite equation is only good for latitude range -60 to 60 degrees, or something along that order, so this may also be at play here as well. Again this points to a place in this code where another validity check (for latitude range) may be in order.

It might behoove us to look at the entire PET result to see if we have reasonable values above/below 60 degrees latitude or so, and/or the input temperature dataset to see if we have all reasonable values. My take at this point is that the climate_indices code itself is behaving as expected but we're feeding it some input data that it's not yet equipped to handle gracefully, leading to the errors we're currently seeing.

Where did you get the original input data? From what I can tell it's maybe one of the [CMIP datasets](https://esgf-node.llnl.gov/projects/esgf-llnl/). Do we know if this data has been properly "cleaned"? My suspicion is that if we tidy up the input data then we'll get around the issues we're seeing here, assuming that the extreme latitudes issue for Thornthwaite PET isn't also a problem.

**Comment by monocongo** [comment]
I am no longer able to reproduce this error using the GPCC precipitation 2.5-degree dataset (as mentioned in #261) or the example datasets provided by @Lixia0911. Tested on Windows 10 and Linux Ubuntu 18.04.

**Comment by Shehabcad** [comment]
during working with BASH & and anaconda windows to generate SPI, I got an error in executing process_grid.py, could you please help me

**Comment by Shehabcad** [comment]
![1](https://user-images.githubusercontent.com/42914908/74085819-5d9a9280-4a7d-11ea-82bb-0eca0dec5f58.JPG)

**Comment by monocongo** [comment]
@Shehabcad from what I can see at first glance:

1. You appear to be using a previous version of the software, as the above screenshot shows climate_indices-0.1.0-py3.7.egg in the site-packages and we're currently at version 1.0.8. The script `process_grid.py` has gone away in the current version.
2. The error here appears to be a missing --output_file_base command line argument. 

My recommendation is to create a fresh Anaconda environment and then install the latest version of this package using `pip` as described in the documentation. Then follow the usage example for monthly or daily SPI. If this fails to work for you then please submit a new issue outlining all the steps you took that led to your error, including environment details, and I will have a look and try to fix the issue for you.

Good luck!

**Comment by Shehabcad** [comment]
Thank you very much, I am following the step in NASA Webinar Applications of GPM IMERG1 Reanalysis for Assessing Extreme Dry and Wet Periods. After your instructions, it works, but I am facing problem with unit mm/hr , even I have downloaded form  data portal monthly data
![Capture](https://user-images.githubusercontent.com/42914908/74108443-d4698580-4b7a-11ea-940a-625b611a519f.JPG)

**Comment by monocongo** [comment]
@Shehabcad Please create a new issue, as your troubles are not related to this one.

The issue here is that you are using a data unit that is unsupported. This is plainly stated in the error message. Apparently you have hourly data, and this package only supports computing indices from daily or monthly input values.

**Comment by umangbuddhdev02** [comment]
@Shehabcad I am facing the same issue, can you help me with it? Thanks.

**Comment by monocongo** [comment]
> @Shehabcad I am facing the same issue, can you help me with it? Thanks.

Please post a new issue with the details of your environment, an example command to reproduce the error, etc. and in that issue description please reference this one if it's relevant. Thanks!
