### ISSUE TITLE
Bug in testing

### ISSUE THREAD

**Issue by khider** [monocongo/climate_indices#258]
I encountered a failure when using the test dataset:
"
____________________________ test_solar_declination ____________________________

    def test_solar_declination():
    
        # make sure invalid arguments raise an error
        pytest.raises(ValueError, eto._solar_declination, 0)
        pytest.raises(ValueError, eto._solar_declination, -1)
        pytest.raises(ValueError, eto._solar_declination, 367)
        pytest.raises(ValueError, eto._solar_declination, 5000)
        pytest.raises(ValueError, eto._solar_declination, np.NaN)
    
        expected_value = -0.313551072399921
        computed_value = eto._solar_declination(30)
        np.testing.assert_equal(
            computed_value,
            expected_value,
>           err_msg="Solar declination not computed as expected",
        )
E       AssertionError: 
E       Items are not equal: Solar declination not computed as expected
E        ACTUAL: -0.31355107239992097
E        DESIRED: -0.313551072399921

tests/test_eto.py:137: AssertionError"

I'm running OSX - 10.14.1  (Mojave)
Anaconda Python 3.6.7

**Comment by monocongo** [comment]
Thanks @khider. It may be that we should instead use something like [`unittest.TestCase.assertAlmostEqual`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual) in this test case to account for minute differences between expected and computed values, such as in this case. My assumption is that this is related to how different platforms have small discrepancies between how they compute values due to differences in how floats are evaluated, etc. [Comparing floating point values is tricky](https://bitbashing.io/comparing-floats.html).

**Comment by monocongo** [comment]
This was fixed by #260. BTW the testing part of the described installation is somewhat of an overkill for normal users and should not be necessary, plans are afoot to update the documentation to provide a bit more clarification. In any event, this should no longer be an issue and thanks for bringing it to my attention. If anything else causes you trouble please let me know, @khider, or if you need additional guidance not available in the documentation, etc. Happy indexing!
