### ISSUE TITLE
scPDSI and PHDI identical for some dates

### ISSUE THREAD

**Issue by Laura-Guillory** [monocongo/climate_indices#336]
**Describe the bug**
Sometimes when calculating the Palmers indices, it will produce results for scPDSI and PHDI that are identical. See the following maps I have produced for my project:

https://i.imgur.com/SXCTtYY.jpg
https://i.imgur.com/RtbOEdr.jpg

I don't know enough about Palmer indices or this software to know whether this is typical behavior, or indicative of a bug, but it doesn't seem right.

**To Reproduce**
This is reproducible with the test data provided with this software. I calculated the Palmer indices using the test data, and the results for scPDSI and PHDI are identical for many dates. I took these screenshots for 2017-02-01. 

https://i.imgur.com/W22vLYD.png
https://i.imgur.com/SyRJjsU.png

The results are not always identical. Sometimes they are slightly different, as I would normally expect. See 2016-09-01:

https://i.imgur.com/2SvxJl0.png
https://i.imgur.com/3y90W7i.png

1. Download test data from https://github.com/monocongo/example_climate_indices/
2. Calculate all Palmer indices using the test data (process_climate_indices --index palmers --periodicity monthly --netcdf_precip input/nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet input/nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc input/nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base results/ --calibration_start_year 1910 --calibration_end_year 2018 --multiprocessing all_but_one)
3. Open scPDSI and PHDI in Panoply or similar NetCDF viewer
4. Compare results for both indices for 2017-02-01 and other dates

**Expected behavior**
I am unsure of what to expect for the Palmer indices, but I would expect results similar to 2016-09-01 than 2017-02-01 (as screenshotted above). Results for scPDSI and PHDI that are identical make me suspicious.

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: Python 3.7.3 

**Additional context**
I would appreciate clarification on whether this is a potential issue, or if these results are typical for the Palmer indices. Thanks for your time.

**Comment by monocongo** [comment]
Thanks for finding this issue, @Laura-Guillory, and for the complete, helpful description. I have forwarded a summary to the scientists I've worked with on this code at NOAA. Hopefully, they will have some insight. My first impression is that this is indeed fishy and merits some investigation/rectification. If you haven't heard back about this in a week or two then feel free to ping me again (this is a very side project for me these days, my apologies for such limited support).

**Comment by Laura-Guillory** [comment]
Thank you for finding the time to look into it.

**Comment by Laura-Guillory** [comment]
Hi @monocongo, did you get any insight on this issue?

**Comment by monocongo** [comment]
Nothing yet, though it was mentioned that this is not a totally unlikely scenario and hence isn't much to worry about. To be honest there is little expertise on this index at NCEI/NOAA where I have contacts and certainly nobody there with PDSI knowledge who can read/debug this Python code. One of my motivations for rewriting the PDSI code (and the other indices contained in this repo) was that there are so many implementations being used in the wild, most of which were apparently cooked up willy nilly over the years, resulting in no standardization and very little common understanding as to how the indices are computed. Because most of these codes were in Fortran and derived from the `pdi.f` code that originated from NOAA (in the 80s?) I thought it'd be good to have an updated version (initially in Python but hopefully later in other languages) that the community could converge on and develop collaboratively as open source in order to finally have standard implementations used across research groups. So that's what we have here and it is what it is. I'll be very happy to have true experts on the Palmer index go through the code and vet it, but I was unsuccessful in getting traction on this effort while I was at NOAA (there always seemed to be bigger fish to fry, resources were always very limited). We have done our best to compare the results against the other Palmer index implementations being used in the field and we're convinced that this is the most solid implementation that gives the most reliable results. However, there is no way to verify this other than putting it to a more rigorous analysis and going through the code to determine the sources of errors if any appear, as looks to be possible in this instance. The code is wide open and I urge you and others who may have the expertise to have at it and please contribute your improvements to this repository so the entire community can benefit and not repeat the process of having everyone go off the reservation running their own custom versions that don't match results with the codes being used by other researchers. Math researchers don't all cook up their own implementations of standard calculations for use in their papers, why are climate scientists doing it?  Imagine if every math paper used custom codes for calculating a square root, replication of results would be impossible, especially since code is rarely shared.

My apologies for what has turned out to be somewhat of a rant here. I'll report back here if I ever get any further clarification, and please do the same if you manage to resolve or gain further insight on this issue. Deke Arndt, Mike Brewer, and Richard Heim are the folks I'd reach out to if you want to bark up the same tree I have. Brian Fuchs and the UNL folks might have some insight as well, plus the WWDT/WRCC in Nevada. I tried for years to get everyone on the same boat and come to some conclusion as to what the best implementation of PDSI is in order to facilitate standardization but it was like herding cats, nobody really seems to have too much of a clue other than PDSI is somewhat of a black magic and there are some codes already that seem to work and are widely used and that's good enough for government work. It's frustrating, to say the least, not scientifically rigorous in my opinion, but that's where we are. Hopefully, things have improved but I'm not optimistic. Good times!

**Comment by Laura-Guillory** [comment]
I will let my team know that it's likely not anything to worry about. Such a shame that there isn't much interest in standardising these implementations! I'll be sure to contribute if I end up trying to improve anything, but sadly I'm more of a programmer than a scientist.
