### ISSUE TITLE
The _os.open didn't work for my dataset and showed "[Errno 22] Invalid argument" error

### ISSUE THREAD

**Issue by Yunlei-Wu** [monocongo/climate_indices#387]
**The bug description:**
I am calculating the SPI using Git bash in win10. 
The OSError: [Errno 22] Invalid argument occurred when I put my dataset as the input file (netcdf_precip). But when I changed the input file as the sample file you gave and it worked well, so I assumed the installation and setting are fine and something wrong with my input file.
 According to my findings, this error usually occurs when the file name contains the symbols which are not allowed in the system. I corrected my file name same as the sample file name, unfortunately, it still didn't work.  I attached the screenshot of the error and the data here. I wish you can give me some hints to solve it. 

**The command I used:**
process_climate_indices --index spi --periodicity monthly --netcdf_precip /D:/Files/Thesis/Data/test/ACCESS_pr_1971_2000.nc --var_name_precip pr --output_file_base /D:/Files/Thesis/Data/test/try --scales  12 --calibration_start_year 1971 --calibration_end_year 2000 --multiprocessing all

**The screenshot of the error:**
![screenshot_of_error](https://user-images.githubusercontent.com/53566712/78883209-77def580-7a59-11ea-82ca-7950c002588c.png)

**The dataset I used as input** (it is too big to upload here):
https://drive.google.com/file/d/1AB2xx2riaYOO-6UohNw-yxhIYiCsEfM6/view?usp=sharing

**Comment by monocongo** [comment]
Thanks @Yunlei-Wu 

I was able to run the command you've used without an error using your input precipitation file:
```
$ pip install climate-indices
Collecting climate-indices
  Downloading climate_indices-1.0.9-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 955 kB/s 
Collecting numba
  Using cached numba-0.48.0-cp38-cp38-manylinux1_x86_64.whl (2.5 MB)
Processing /home/james/.cache/pip/wheels/a5/2b/b5/05758d5828d65f2adef8fbb5d5484e4adb946ae1827a973a01/toolz-0.10.0-py3-none-any.whl
Collecting nco
  Using cached nco-1.0.0-py2.py3-none-any.whl (10 kB)
Collecting dask
  Downloading dask-2.14.0-py3-none-any.whl (794 kB)
     |████████████████████████████████| 794 kB 5.3 MB/s 
Collecting numpy
  Downloading numpy-1.18.2-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
     |████████████████████████████████| 20.6 MB 4.3 MB/s 
Collecting scipy
  Using cached scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
Collecting netcdf4
  Using cached netCDF4-1.5.3-cp38-cp38-manylinux1_x86_64.whl (4.0 MB)
Collecting xarray
  Downloading xarray-0.15.1-py3-none-any.whl (668 kB)
     |████████████████████████████████| 668 kB 57.0 MB/s 
Requirement already satisfied: setuptools in /home/james/miniconda3/envs/indices/lib/python3.8/site-packages (from numba->climate-indices) (46.1.3.post20200325)
Collecting llvmlite<0.32.0,>=0.31.0dev0
  Using cached llvmlite-0.31.0-cp38-cp38-manylinux1_x86_64.whl (20.2 MB)
Collecting cftime
  Downloading cftime-1.1.1.2-cp38-cp38-manylinux1_x86_64.whl (312 kB)
     |████████████████████████████████| 312 kB 53.9 MB/s 
Collecting pandas>=0.25
  Downloading pandas-1.0.3-cp38-cp38-manylinux1_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 14.5 MB/s 
Collecting pytz>=2017.2
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting python-dateutil>=2.6.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting six>=1.5
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: llvmlite, numpy, numba, toolz, nco, dask, scipy, cftime, netcdf4, pytz, six, python-dateutil, pandas, xarray, climate-indices
Successfully installed cftime-1.1.1.2 climate-indices-1.0.9 dask-2.14.0 llvmlite-0.31.0 nco-1.0.0 netcdf4-1.5.3 numba-0.48.0 numpy-1.18.2 pandas-1.0.3 python-dateutil-2.8.1 pytz-2019.3 scipy-1.4.1 six-1.14.0 toolz-0.10.0 xarray-0.15.1

$ process_climate_indices --index spi --periodicity monthly --netcdf_precip ACCESS_pr_1971_2000.nc --var_name_precip pr --output_file_base try --scales 12 --calibration_start_year 1971 --calibration_end_year 2000 --multiprocessing all
2020-04-09  10:32:36 INFO Start time:    2020-04-09 10:32:36.127665
2020-04-09  10:32:37 INFO Computing 12-month SPI/Pearson
2020-04-09  10:33:14 INFO Computing 12-month SPI/Gamma
2020-04-09  10:33:33 INFO End time:      2020-04-09 10:33:33.755907
2020-04-09  10:33:33 INFO Elapsed time:  0:00:57.628242
```

I tested this on Linux (Ubuntu 18.04), I apologize I don't have a Windows machine to use for testing.

The error shown in your output looks like an issue with the call to NCO's `ncpdq` which is used in our code [here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L1533). It looks like there is a mixup with the backward slash and forward slash separators and/or perhaps the paths of the input file and the temporary file used within NCO is not being handled correctly (this may be what's happening in line 327 of `nco.py`, see the stack trace). I am hard-pressed to comment further on this as it is only conjecture at this point.

One thing you might try is to reorder the dimensions of your precipitation file outside of this code and then use that reordered file as the input to the climate_indices script. If this works then it points to an issue in the NCO package where it is not behaving as expected when running on Windows. The NCO software is developed on Linux and not very well tested on Windows so this is possibly something that the developers of NCO haven't seen before in their testing, you may want to ask them about it.

So here's what I'd try:
1. Reorder the dimensions of the precipitation file outside of this script, i.e. run this NCO command:
```
$ ncpdq -a "lat,lon,time" -in ACCESS_pr_1971_2000.nc -out reordered_ACCESS_pr_1971_2000.nc
```
2. Use the reordered file as input to the script from this package for computing SPI:
```
$ process_climate_indices --index spi --periodicity monthly --netcdf_precip reordered_ACCESS_pr_1971_2000.nc --var_name_precip pr --output_file_base try --scales 12 --calibration_start_year 1971 --calibration_end_year 2000 --multiprocessing all
```
By doing the reordering of the dimensions outside of this script (in step 1 above) it will bypass the file preparation step (within step 2), so if there is a problem with NCO then it will show up when you try to reorder using NCO (I doubt that this will happen), otherwise that will perhaps reveal that this is an issue with the Python NCO wrapper when being run on Windows.

**Comment by Yunlei-Wu** [comment]
Thank you for your quick reply, @monocongo 
The reorder operation works well for this dataset. Hopefully, it also works for other datasets. 
1. Do you recommend to calculate these climate indices with Ubuntu? I mean it might reduce many avoidable problems.
2. And I wonder what the point to set the calibration period?  In the climate toolbox of Matlab, it doesn't have a parameter for the calibration period and the expected results for users are indices values over pixels.
I think it might be useful to set a parameter to select the period that you want to do the calculation if the input file contains a much larger period dataset.

**Comment by monocongo** [comment]
We've written the code to work with Python on any platform. With that being said I do use Linux/Ubuntu myself for development/maintenance of this code, and I find it easier to work with in general.

The calibration period is an artifact for NOAA/NCEI processing, as their original code used a specific calibration period so we included that in this package to allow for specifying a calibration period. In general you get more useful results if you use the full period of record as the calibration period (i.e. no calibration period at all).

Your idea of allowing users to select the computation period is interesting, feel free to submit an issue requesting this as a new feature.

It appears that we may have discovered an issue with [pynco](https://github.com/nco/pynco) when [reordering dimensions of a NetCDF](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L1533) when running this code on Windows, as this doesn't appear to happen when running this package on Linux. It might be interesting to cook up a small example of this happening outside of the context of this issue/package in order to help the developers of that package to isolate/fix this problem.

**Comment by liushuming75** [comment]
![image](https://user-images.githubusercontent.com/82938738/140551714-03acb872-bce5-4085-a53d-40ae8bb90ad6.png)
I am a new Linux player, I have downloaded the climate module, but why this error is reported, can you help me?
