### ISSUE TITLE
Is there any way to compute PET Hargreaves method using xr.apply_ufunc() ? 

### ISSUE THREAD

**Issue by SouhailAB** [monocongo/climate_indices#428]

**Comment by monocongo** [comment]
No, unfortunately not. Hargreaves has not yet been implemented, see issue #102 

There is an excellent repository with various PET functions [here](https://pyeto.readthedocs.io/en/latest/). It may be possible to somehow utilize the Hargreaves function there rather than reinvent the wheel here. I have had plans to add Hargreaves for quite a while, but still haven't found the time...
