### ISSUE TITLE
Change license to GPLv3

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#444]
We want contributions and using the GPLv3 may help encourage/nudge that more than the BSD license currently in place.

**Comment by WeatherGod** [comment]
Consider this a vote against that. I am about to try adding a feature that we need at my workplace and if the license changes to GPL, then I have to back off as the GPL would not be an approved license to use for this particular project. One of the main reasons I came upon this project a couple months ago is because a similar project was GPL'ed and I couldn't use it.

**Comment by WeatherGod** [comment]
I am also curious as to why you think switching licenses would encourage more contributions? Coming from the scipy ecosystem (I am a matplotlib developer and have some contributions to numpy and other projects), the BSD license wasn't a turn-off for me at all. Community-building is the key thing, and making the project more accessible and useful will encourage more contributions. Also, active development is important (seeing it being almost a year since the last commit sends the wrong signal to newcomers).

**Comment by monocongo** [comment]
Thanks for this feedback, @WeatherGod  The idea of changing the license was a desperate and misguided attempt to get some help. I rarely hear of users except when someone has an issue, and it's quite encouraging to know that you're actively using this package. You're exactly the kind of user I want, so if this negatively impacts you then it's a bad idea right from the jump. The primary users that I'm aware of (at NOAA) have no apparent interest in contributing to the project, they can barely use git. But they've also talked big about how they can improve performance by better leveraging xarray and if they pull that off then I want that code included here if I can get it, and I thought that maybe tightening the license will facilitate that. Frustration from working with freeloaders led me to this point, but this is open source, so what did I really expect? It's not as if those scientists will see a license change and then all of a sudden start playing ball with us. I am not a smart man.

There has been no proper development on this package for a while but I've remained active in addressing user issues. But this project has become unkempt and I don't have the time to properly maintain it on my own. For example, the tests and hence the CI are broken and there are two outstanding PRs that I'm unqualified to evaluate/approve (a proper climate scientist or meteorologist should scientifically vet these). The broken tests/CI issue must have been resolved by somebody who uses this package in a serious manner, and if so I'd like to get those contributions. If the features added by those two PRs are useful to the user community then someone with more scientific credibility than I have needs to pitch in and help with those. I want to keep this project alive and in good shape, but my day job takes most of my bandwidth now.

**Comment by WeatherGod** [comment]
Sorry to hear of your experience. I would encourage you to try presenting at a SciPy conference. In a typical year, a substantial portion of its attendees are in the geosciences. Attendees are also either already programming-literate, or are learning the necessary skills at the conference through its many tutorials and coding sprints (disclosure: I used to be on the tutorials committee).

Thank you for reconsidering your position with the software license. While I can't guarantee that I will be a permanent user of the software (droughts aren't my typical area of work), if things go well, this will play a part in an operational product. So, ideally, you'll know when things break for us!
