### ISSUE TITLE
Remove pycurl dependency

### ISSUE THREAD

**Issue by kikocorreoso** [monocongo/climate_indices#54]
You are using `pycurl` to perform file downloading. I think you could easily remove this dependency using `urllib` included in the *stdlib* so users don't have to install a third party dependency.

Even, you could remove the `retrieve_file` function from the `utils` module as you could use directly the following:

Now you have:

```python
from indices_python.utils import retrieve_file

retrieve_file(url, local_file)
```

You could remove `retrieve_file` function and `pycurl` dependency and do the same using:

```python
from urllib import request

request.urlretrieve(url, local_file)
```

So less dependencies, less code, less tests using a battle tested stdlib functionality. WIN-WIN.

**Comment by monocongo** [comment]
Absolutely, let me try it out and test, I don't see any downsides. I tried urllib, urllib2, and wget without quick success and instead I went with what's present because I got it to work fastest (a little ironic since it's actually more lines of code). This looks like a drop in no-brainer replacement.

**Comment by monocongo** [comment]
Now I've remembered why I avoided urllib.request.urlretrieve and urllib.request.urlopen in the past, a code analysis (CodeFactor) highlighted these calls as medium risk: https://docs.openstack.org/bandit/latest/api/bandit.blacklists.html?highlight=urllib

I don't understand enough about this yet to know if this can be safely ignored or not, apparently I was cautious enough about it before, but I like having less lines of code, sticking with standard libraries, etc. so I'm OK with this for now, unless somebody can convince me otherwise.

**Comment by kikocorreoso** [comment]
Check this: https://www.bleepingcomputer.com/news/security/ten-malicious-libraries-found-on-pypi-python-package-index/

Maybe the warning is due to this: urlib instead of url**l**ib...

**Comment by monocongo** [comment]
Very interesting, also with an aside relevant to issue #55:

> "On a side note, and unrelated to the attack vector, NBU also advises Python developers to avoid using "pip" — a Python package installer — when downloading Python libraries, as pip does not support cryptographic signatures."

**Comment by kikocorreoso** [comment]
If tests are passing after removing `pycurl` dependency I thing this could be closed.
